### PR TITLE
Added the !savage command for @Jim

### PR DESCRIPTION
**Pull request by Nishnha**
Added the file savage.py in /scripts/
- The command !savage will post the link http://i.imgur.com/aE41Aoo.gif

### CODE REVIEW

**Comment by mhijazi1** [comment]
This looks good, but as were waiting on braxton's refactor to go through, this will need to be chaned wonce that goes through. Mind holding off and fixing it then?

**Comment by Nishnha** [comment]
@mhijazi1 Can do.
@arshbot whoops. Well looks like it will be a non-issue when it's actually implemented!

**Comment by ghost** [comment]
This is actually not functional at the moment. You have to wrap your string in an array or it will post each character as a message. Kind of moot at this point with the incoming refactor, but I just thought I'd let you know that this doesn't quite work.

**Comment by ghost** [comment]
Lol the multiple conversations at one time

**Comment by mhijazi1** [comment]
Please pull from latest so this is now up to date with the latest changes. Response objects are now a thing so make sure your scripts returns one. If you need explanation for how todo this please talk to @braxton-mclean

**Comment by ghost** [comment]
Hey @Nishnha do you want to have another swing at this? Formatting your results and shaping the script like the helloworld.py script would be good.

**Pull request closed without merging**
