### PR TITLE
Bring on the catfacts!

### PR DESCRIPTION
**Pull request by maren-mclean**

### CODE REVIEW

**Review by bcabio — CHANGES_REQUESTED** [review]
Does not give output if you add a parameter to catfact

**Comment by maren-mclean** [comment]
To address this add `args=None` as the second parameter to the run function in the script. This should also be done for fortune.py

**Comment by Litagano-M** [comment]
@bcabio @braxton-mclean What should the parameter do?

**Comment by maren-mclean** [comment]
The parameter is just a list of arguments that is passed to the function. In practice you can always append an argument to any script since there is no way to strongly enforce that on the slack side.
Setting the parameter args to have a default of `None` will mean if no arguments are passed it won't break, but if there are it won't either.

**Comment by Litagano-M** [comment]
Ah, so it's just to prevent the code from breaking. I thought I needed to do something with the passed in parameter in the code.

**Review by bcabio — APPROVED** [review]

**Pull request merged**
